
import React from 'react';
import { ScanResult, ManualStep } from '../types';
import { generateScannerManual } from '../utils/manualGenerator';
import { BookOpen, ChevronRight, CornerDownRight, X, Printer } from 'lucide-react';

interface Props {
  data: ScanResult;
  onClose: () => void;
}

const StepRenderer: React.FC<{ step: ManualStep; depth?: number }> = ({ step, depth = 0 }) => {
  return (
    <div className={`mb-2 ${depth > 0 ? 'ml-6 border-l border-slate-700 pl-4' : ''}`}>
      <div className="flex items-start gap-2">
        {depth > 0 && <CornerDownRight className="w-4 h-4 text-slate-500 mt-1 flex-shrink-0" />}
        <p className="text-slate-300 font-mono-tech text-sm leading-relaxed">
          {step.text}
          {step.value && (
            <span className="ml-2 inline-block bg-amber-900/40 text-amber-300 px-2 py-0.5 rounded border border-amber-700/50 font-bold select-all">
              {step.value}
            </span>
          )}
        </p>
      </div>
      {step.subSteps && (
        <div className="mt-2">
          {step.subSteps.map((sub, idx) => (
            <StepRenderer key={idx} step={sub} depth={depth + 1} />
          ))}
        </div>
      )}
    </div>
  );
};

export const ProgrammingManual: React.FC<Props> = ({ data, onClose }) => {
  const manual = generateScannerManual(data);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm print:bg-white print:absolute print:inset-auto">
      <div className="bg-slate-900 w-full max-w-4xl h-[90vh] rounded-xl border border-slate-700 shadow-2xl flex flex-col print:border-none print:shadow-none print:h-auto print:bg-white print:text-black">
        
        {/* Header */}
        <div className="p-6 border-b border-slate-800 flex justify-between items-center bg-slate-950 rounded-t-xl print:bg-white print:border-b-2 print:border-black">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-blue-600/20 rounded-lg print:hidden">
              <BookOpen className="w-6 h-6 text-blue-400" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white font-mono-tech print:text-black">PROGRAMMING MANUAL</h2>
              <p className="text-sm text-slate-400 print:text-gray-600">Target: Uniden SDS100 / SDS200</p>
            </div>
          </div>
          <div className="flex gap-2 print:hidden">
            <button 
              onClick={handlePrint}
              className="p-2 hover:bg-slate-800 rounded-lg transition-colors text-slate-400 hover:text-white"
              title="Print Manual"
            >
              <Printer className="w-5 h-5" />
            </button>
            <button 
              onClick={onClose}
              className="p-2 hover:bg-red-900/30 rounded-lg transition-colors text-slate-400 hover:text-red-400"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-8 space-y-12 print:overflow-visible">
          <div className="mb-8 text-center print:text-left">
            <h1 className="text-3xl font-bold text-white mb-2 font-mono-tech uppercase print:text-black">{manual.title}</h1>
            <p className="text-slate-500 print:text-gray-500">Generated by Boy & A Scanner AI Agent</p>
          </div>

          {manual.sections.map((section, idx) => (
            <section key={idx} className="bg-slate-800/30 rounded-xl p-6 border border-slate-700/50 print:bg-transparent print:border print:border-gray-300 print:mb-6 print:break-inside-avoid">
              <h3 className="text-xl font-bold text-cyan-400 mb-2 font-mono-tech flex items-center gap-2 print:text-blue-700">
                <ChevronRight className="w-5 h-5" />
                {section.title}
              </h3>
              {section.description && (
                <p className="text-slate-400 text-sm mb-6 ml-7 italic print:text-gray-600">{section.description}</p>
              )}
              
              <div className="space-y-4 ml-2">
                {section.steps.map((step, sIdx) => (
                  <StepRenderer key={sIdx} step={step} />
                ))}
              </div>
            </section>
          ))}
          
          <div className="mt-12 p-6 bg-amber-900/10 border border-amber-900/30 rounded-lg print:border-black print:bg-gray-100">
            <h4 className="text-amber-500 font-bold mb-2 font-mono-tech uppercase print:text-black">Important Note</h4>
            <p className="text-sm text-slate-400 print:text-gray-800">
                This manual is generated based on the current data snapshot. Frequencies and Talkgroup IDs must be entered exactly as shown. 
                Ensure your SDS100/200 has the latest firmware and appropriate paid upgrades (DMR/NXDN) if scanning those system types.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
