
import JSZip from 'jszip';
import { ScanResult, TripResult, Agency, TrunkedSystem } from '../types';

/**
 * Sentinel Exporter
 * 
 * Generates a ZIP file containing Sentinel-formatted CSV files
 * for easy copy-paste import into Uniden Sentinel software
 * (SDS100 / SDS200 programming).
 */

// --- CSV Formatting Helpers ---

const esc = (str: string | undefined): string => {
    if (!str) return '';
    const s = String(str).replace(/"/g, '""');
    if (s.includes(',') || s.includes('"') || s.includes('\n')) return `"${s}"`;
    return s;
};

const csvRow = (cells: string[]): string => cells.map(esc).join(',');

// --- Conventional Channels CSV ---

function buildConventionalCSV(agencies: Agency[], locationName: string): string {
    const lines: string[] = [];

    // Header matches Sentinel's conventional channel editor column order
    lines.push('Frequency,Name,Modulation,CTCSS_DCS,Department,Tag,System');

    for (const agency of agencies) {
        for (const freq of (agency.frequencies || [])) {
            const modulation = freq.mode || 'FM';
            const tone = freq.tone || freq.nac || freq.colorCode || '';
            const name = (freq.alphaTag || freq.description || '').substring(0, 16);

            lines.push(csvRow([
                freq.freq,
                name,
                modulation,
                tone,
                agency.name,
                freq.tag || agency.category,
                locationName
            ]));
        }
    }

    return lines.join('\n');
}

// --- Trunked System CSV ---

function buildTrunkedCSV(system: TrunkedSystem): string {
    const lines: string[] = [];

    // Section 1: System Info
    lines.push('# SYSTEM INFORMATION');
    lines.push(`# Name: ${system.name}`);
    lines.push(`# Type: ${system.type}`);
    lines.push(`# Location: ${system.location}`);
    lines.push('');

    // Section 2: Site Frequencies (Control Channels)
    if (system.frequencies && system.frequencies.length > 0) {
        lines.push('# SITE FREQUENCIES - Enter these in Sentinel under Edit Site > Set Frequencies');
        lines.push('Site_Frequency,Use');
        for (const f of system.frequencies) {
            lines.push(csvRow([f.freq, f.use || 'Control']));
        }
        lines.push('');
    }

    // Section 3: Talkgroups - columns match Sentinel's talkgroup editor
    lines.push('# TALKGROUPS - Select all rows below and paste into Sentinel talkgroup editor');
    lines.push('TGID,Name,Tag,Mode,Description');

    for (const tg of (system.talkgroups || [])) {
        lines.push(csvRow([
            tg.dec,
            (tg.alphaTag || '').substring(0, 16),
            tg.tag || '',
            tg.mode || 'D',
            tg.description || ''
        ]));
    }

    return lines.join('\n');
}

// --- Quick Reference (plain text for field use) ---

function buildQuickReference(data: ScanResult): string {
    const lines: string[] = [];
    const divider = '═'.repeat(60);
    const thinDiv = '─'.repeat(60);

    lines.push(divider);
    lines.push(`  QUICK REFERENCE: ${data.locationName}`);
    lines.push(`  Generated by Boy & A Scanner`);
    lines.push(`  ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);
    lines.push(divider);
    lines.push('');

    // Conventional
    const agencies = data.agencies || [];
    if (agencies.length > 0) {
        lines.push('▸ CONVENTIONAL FREQUENCIES');
        lines.push(thinDiv);
        for (const agency of agencies) {
            lines.push(`  ${agency.name.toUpperCase()} [${agency.category}]`);
            for (const freq of (agency.frequencies || [])) {
                const tone = freq.tone ? ` PL ${freq.tone}` : '';
                const nac = freq.nac ? ` NAC ${freq.nac}` : '';
                const cc = freq.colorCode ? ` CC ${freq.colorCode}` : '';
                const name = freq.alphaTag || freq.description;
                lines.push(`    ${freq.freq.padEnd(12)} ${freq.mode.padEnd(5)} ${name}${tone}${nac}${cc}`);
            }
            lines.push('');
        }
    }

    // Trunked
    const systems = data.trunkedSystems || [];
    if (systems.length > 0) {
        lines.push('▸ TRUNKED SYSTEMS');
        lines.push(thinDiv);
        for (const sys of systems) {
            lines.push(`  ${sys.name.toUpperCase()} (${sys.type})`);
            lines.push(`  Site: ${sys.location}`);

            if (sys.frequencies && sys.frequencies.length > 0) {
                const freqStr = sys.frequencies.map(f => `${f.freq}${f.use ? ` [${f.use}]` : ''}`).join(', ');
                lines.push(`  Control Freqs: ${freqStr}`);
            }

            lines.push(`  Talkgroups: ${(sys.talkgroups || []).length}`);

            // List top 15 talkgroups for quick reference
            const topTGs = (sys.talkgroups || []).slice(0, 15);
            for (const tg of topTGs) {
                lines.push(`    ${tg.dec.padEnd(8)} ${(tg.alphaTag || '').padEnd(16)} ${tg.tag || ''}`);
            }
            if ((sys.talkgroups || []).length > 15) {
                lines.push(`    ... and ${(sys.talkgroups || []).length - 15} more (see CSV files)`);
            }
            lines.push('');
        }
    }

    lines.push(divider);
    lines.push('  DO NOT TRANSMIT ON ANY OF THESE FREQUENCIES');
    lines.push(divider);

    return lines.join('\n');
}

// --- Import Instructions ---

function buildImportGuide(data: ScanResult): string {
    const hasTrunked = (data.trunkedSystems || []).length > 0;
    const hasConventional = (data.agencies || []).length > 0;

    const lines: string[] = [];

    lines.push('╔══════════════════════════════════════════════════════════╗');
    lines.push('║    BOY & A SCANNER - SENTINEL IMPORT GUIDE             ║');
    lines.push('║    For Uniden SDS100 / SDS200                          ║');
    lines.push('╚══════════════════════════════════════════════════════════╝');
    lines.push('');
    lines.push(`Location: ${data.locationName}`);
    lines.push(`Generated: ${new Date().toLocaleString()}`);
    lines.push('');
    lines.push('════════════════════════════════════════════════════════════');
    lines.push('  BEFORE YOU START');
    lines.push('════════════════════════════════════════════════════════════');
    lines.push('');
    lines.push('1. Connect your SDS100/200 to your computer via USB.');
    lines.push('2. Open Uniden Sentinel software.');
    lines.push('3. Click "Read Scanner" to load current programming.');
    lines.push('4. Create a new Favorites List:');
    lines.push('   Menu > Manage Favorites Lists > New Favorites List');
    lines.push(`   Name it: "${data.locationName.substring(0, 12)}"`);
    lines.push('');

    if (hasConventional) {
        lines.push('════════════════════════════════════════════════════════════');
        lines.push('  STEP A: IMPORT CONVENTIONAL FREQUENCIES');
        lines.push('════════════════════════════════════════════════════════════');
        lines.push('');
        lines.push('File: Conventional_Channels.csv');
        lines.push('');
        lines.push('1. In Sentinel, select your Favorites List.');
        lines.push('2. Click "New System" > select "Conventional".');
        lines.push('3. Name it "Local Analog" or similar.');
        lines.push('4. Create a Department (e.g., "Police", "Fire").');
        lines.push('5. Open the CSV file in Excel or Google Sheets.');
        lines.push('6. Select the data rows (skip the header).');
        lines.push('7. In Sentinel, click on the first empty row in the');
        lines.push('   channel editor.');
        lines.push('8. Copy the Frequency column from your spreadsheet');
        lines.push('   and paste it into the Frequency field in Sentinel.');
        lines.push('9. Repeat for Name, Modulation, and CTCSS/DCS columns.');
        lines.push('');
        lines.push('TIP: You can select multiple cells in Excel and paste');
        lines.push('     them into Sentinel to fill multiple rows at once.');
        lines.push('');
    }

    if (hasTrunked) {
        lines.push('════════════════════════════════════════════════════════════');
        lines.push('  STEP B: IMPORT TRUNKED SYSTEMS');
        lines.push('════════════════════════════════════════════════════════════');
        lines.push('');
        lines.push('For each Trunked_*.csv file:');
        lines.push('');
        lines.push('1. In Sentinel, select your Favorites List.');
        lines.push('2. Click "New System" > select the system type');
        lines.push('   (shown at the top of each CSV file as a comment).');
        lines.push('3. Name the system as shown in the CSV header.');
        lines.push('4. Go to "Edit Site" > "New Site".');
        lines.push('5. Under "Set Frequencies", enter all Site Frequencies');
        lines.push('   listed in the CSV file.');
        lines.push('6. Create Departments and add Talkgroups:');
        lines.push('   - Open the CSV in Excel/Sheets');
        lines.push('   - Select the TGID and Name columns');
        lines.push('   - Paste into Sentinel\'s talkgroup editor');
        lines.push('');
        lines.push('TIP: Group talkgroups by their "Tag" column to create');
        lines.push('     logical departments (e.g., Police, Fire, EMS).');
        lines.push('');
    }

    lines.push('════════════════════════════════════════════════════════════');
    lines.push('  FINAL STEPS');
    lines.push('════════════════════════════════════════════════════════════');
    lines.push('');
    lines.push('1. Review all entries in Sentinel for accuracy.');
    lines.push('2. Click "Write Scanner" to upload to your SDS100/200.');
    lines.push('3. On the scanner, go to:');
    lines.push('   Menu > Set Scan Selection > Select Lists to Monitor');
    lines.push('   Ensure your new list is enabled.');
    lines.push('4. Press [Scan/Search] to begin scanning!');
    lines.push('');
    lines.push('════════════════════════════════════════════════════════════');
    lines.push('  NOTES');
    lines.push('════════════════════════════════════════════════════════════');
    lines.push('');
    lines.push('• Data source: RadioReference.com / AI Grounded Search');
    lines.push('• DO NOT TRANSMIT on any of these frequencies.');
    lines.push('• Ensure your scanner firmware is up to date.');
    lines.push('• DMR/NXDN requires paid upgrade keys from Uniden.');
    lines.push('');
    lines.push('Generated by Boy & A Scanner (boyandascanner.com)');

    return lines.join('\n');
}

// --- Filename Sanitizer ---

function safeFilename(name: string): string {
    return name.replace(/[^a-zA-Z0-9_\- ]/g, '').replace(/\s+/g, '_').substring(0, 40);
}

// --- Main Export Functions ---

/**
 * Export a single scan result as a Sentinel-compatible ZIP
 */
export async function exportSentinelZip(data: ScanResult): Promise<void> {
    const zip = new JSZip();
    const locName = safeFilename(data.locationName);

    // Import Guide
    zip.file('README_IMPORT_GUIDE.txt', buildImportGuide(data));

    // Quick Reference
    zip.file('Quick_Reference.txt', buildQuickReference(data));

    // Conventional CSV
    const agencies = data.agencies || [];
    if (agencies.length > 0) {
        zip.file('Conventional_Channels.csv', buildConventionalCSV(agencies, data.locationName));
    }

    // Trunked CSVs (one per system)
    const systems = data.trunkedSystems || [];
    for (let i = 0; i < systems.length; i++) {
        const sys = systems[i];
        const sysName = safeFilename(sys.name);
        zip.file(`Trunked_${i + 1}_${sysName}.csv`, buildTrunkedCSV(sys));
    }

    // Generate and download ZIP
    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `SDS100_${locName}.zip`;
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

/**
 * Export a full trip result as a Sentinel-compatible ZIP
 */
export async function exportTripSentinelZip(trip: TripResult): Promise<void> {
    const zip = new JSZip();
    const tripName = `${safeFilename(trip.startLocation)}_to_${safeFilename(trip.endLocation)}`;
    const locations = trip.locations || [];

    // Master import guide (uses first location as template for instructions)
    if (locations.length > 0) {
        const masterGuide = buildImportGuide(locations[0].data);
        zip.file('README_IMPORT_GUIDE.txt', masterGuide);
    }

    // Per-location folders
    for (let locIdx = 0; locIdx < locations.length; locIdx++) {
        const loc = locations[locIdx];
        const folderName = `Zone_${locIdx + 1}_${safeFilename(loc.locationName)}`;
        const folder = zip.folder(folderName)!;

        // Quick Reference
        folder.file('Quick_Reference.txt', buildQuickReference(loc.data));

        // Conventional
        const agencies = loc.data.agencies || [];
        if (agencies.length > 0) {
            folder.file('Conventional_Channels.csv', buildConventionalCSV(agencies, loc.locationName));
        }

        // Trunked
        const systems = loc.data.trunkedSystems || [];
        for (let i = 0; i < systems.length; i++) {
            const sys = systems[i];
            const sysName = safeFilename(sys.name);
            folder.file(`Trunked_${i + 1}_${sysName}.csv`, buildTrunkedCSV(sys));
        }
    }

    // Generate and download
    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `SDS100_Trip_${tripName}.zip`;
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
